/**
 * Soru slug'larının (server/src/examQuestions.js ile birebir aynı sırada/isimde)
 * Türkçe kısa başlıklara eşlemesi. Öğretmen/admin panelindeki Soru Analizi
 * ekranında öğrencinin gördüğü sorunun ne olduğunu anlaşılır kılmak için kullanılır.
 */
export const QUESTION_TITLES: Record<string, string> = {
    'pattern': 'Desen Kopyalama',
    'odd-direction': 'Farklı Yöne Bakan',
    'shade-sorting': 'Renk Tonu Sıralama',
    'number-sequence': 'Sayı Dizisi',
    'symbol-matching': 'Sembol Eşleştirme',
    'multi-condition-selection': 'Çoklu Koşul Seçimi',
    'animal-position': 'Hayvan Konumu',
    'pattern-2': 'Desen Kopyalama 2',
    'shape-coloring': 'Şekil Boyama',
    'liquid-selection': 'Sıvı Seçimi',
    'longest-rope': 'En Uzun İp',
    'letter-matching': 'Harf Eşleştirme',
    'shape-pattern': 'Şekil Örüntüsü',
    'board-letter-matching': 'Tahtada Harf Eşleştirme',
    'shape-to-color-match': 'Şekilden Renge Eşleştirme',
    'sequence-rule-breaker': 'Kuralı Bozan Sırada',
    'living-things': 'Canlılar',
    'traffic-sign-matching': 'Trafik İşareti Eşleştirme',
    'abacus-counting': 'Abaküs Sayma',
    'dot-pattern-drawing': 'Nokta Deseni Çizme',
    'fruit-count-matching': 'Meyve Sayısı Eşleştirme',
    'find-most-balls': 'En Çok Top',
    'shadow-matching': 'Gölge Eşleştirme',
    'letter-sequence': 'Harf Dizisi',
    'identical-pattern': 'Aynı Desen',
    'match-size': 'Boyut Eşleştirme',
    'grid-coloring': 'Izgara Boyama',
    'find-same-symbols': 'Aynı Sembolü Bulma',
    'find-numbers': 'Sayı Bulma',
    'find-reversed-e': 'Ters E Bulma',
    'count-and-add': 'Sayıp Toplama',
    'rhythmic-counting': 'Ritmik Sayma',
    'top-view': 'Kuşbakışı Görünüm',
    'box-coloring': 'Kutu Boyama',
    'triangle-size': 'Üçgen Boyutu',
    'flower-coloring': 'Çiçek Boyama',
    'not-in-word': 'Kelimede Olmayan Harf',
    'finding-green-lines': 'Yeşil Çizgileri Bulma',
    'incorrect-numbers': 'Yanlış Sayılar',
    'water-capacity': 'Su Kapasitesi',
    'fruit-size-ranking': 'Meyve Boyut Sıralama',
    'elderly-people': 'Yaşlı İnsanlar',
    'find-different': 'Farklıyı Bulma',
    'cylinder-selection': 'Silindir Seçimi',
    'pattern-completion': 'Deseni Tamamlama',
    'shape-counting': 'Şekil Sayma',
    'happy-children': 'Mutlu Çocuklar',
    'different-mountain': 'Farklı Dağ',
    'letter-grid': 'Harf Izgarası',
    'ice-cream-shape': 'Dondurma Şekli',
    'most-colorful-ball': 'En Renkli Top',
    'cat-position': 'Kedinin Konumu',
    'dot-grid-copy': 'Nokta Izgarası Kopyalama',
    'bike-matching': 'Bisiklet Eşleştirme',
    'pencil-matching': 'Kalem Eşleştirme',
    'symbol-grid-copy': 'Sembol Izgarası Kopyalama',
    'ball-matching': 'Top Eşleştirme',
    'orange-different': 'Farklı Portakal',
    'river-branches': 'Nehir Kolları',
    'symbol-grid-matching': 'Sembol Izgarası Eşleştirme',
    'shape-match-find': 'Eşini Bulma',
    'count-apples': 'Elma Sayma',
    'ball-sequence': 'Top Dizisi',
    'snake-letter': 'Yılan Harfi',
    'letter-color-match': 'Harf Renk Eşleştirme',
    'fruit-subtraction': 'Meyve Çıkarma',
    'triangle-match': 'Üçgen Tamamlama',
    'set-match': 'Küme Eşleştirme',
    'profession-matching': 'Meslek Eşleştirme',
    'fruit-basket': 'Meyve Sepeti',
    'flower-order': 'Çiçek Sıralama',
    'symbol-color-match': 'Sembol Renk Eşleştirme',
    'object-addition': 'Nesne Toplama',
    'symbol-block-match': 'Sembol Bloğu Eşleştirme',
    'shade-sorting-2': 'Renk Tonu Sıralama 2',
    'balance-scale': 'Terazi Dengesi',
    'two-feature-filter': 'İki Özellik Filtreleme',
    'subtle-difference': 'İnce Fark',
    'letter-hunt': 'Harf Avı',
    'missing-number': 'Eksik Sayı',
    'odd-category-out': 'Kategoriye Uymayan',
    'mirror-letter': 'Ayna Harfi',
    'letter-count': 'Harf Sayma',
    'first-letter-match': 'İlk Harf Eşleştirme',
    'count-difference': 'Sayı Farkı',
    'number-ordering': 'Sayı Sıralama',
    'rotate-shape': 'Şekli Döndürme',
    'count-sides': 'Kenar Sayma',
    'sort-by-size': 'Boyuta Göre Sıralama',
    'same-word-find': 'Aynı Kelimeyi Bulma',
    'count-given-color': 'Verilen Rengi Sayma',
    'star-difference': 'Yıldız Farkı',
    'fruit-sequence': 'Meyve Dizisi',
    'arrow-grid-copy': 'Ok Izgarası Kopyalama',
    'color-pattern-completion': 'Renk Deseni Tamamlama',
    'number-grid-match': 'Sayı Izgarası Eşleştirme',
    'digit-row-finder': 'Rakam Sırası Bulma',
    'number-color-match': 'Sayı Renk Eşleştirme',
    'symbol-sequence-match': 'Sembol Dizisi Eşleştirme',
    'shape-matrix': 'Şekil Matrisi',
    'school-profession': 'Okul Meslekleri',
    'tallest-animal': 'En Uzun Hayvan',
    'shape-corners': 'Şekil Köşeleri',
    'pencil-matching-v2': 'Kalem Eşleştirme 2',
    'shape-count-coloring': 'Şekil Sayısına Göre Boyama',
    'sport-matching': 'Spor Eşleştirme',
    'letter-counting': 'Harf Sayma',
    'elephant-direction': 'Fil Yönü',
    'symbol-addition': 'Sembol Toplama',
    'grid-coloring-numbers': 'Sayılara Göre Izgara Boyama',
    'child-bicycle-matching': 'Çocuk Bisiklet Eşleştirme',
    'symbol-pair-matching': 'Sembol Çifti Eşleştirme',
    'house-door-direction': 'Ev Kapı Yönü',
    'count-matching-v2': 'Sayı Eşleştirme 2',
    'rectangle-selection': 'Dikdörtgen Seçimi',
    'count-six-selection': 'Altı Sayısını Seçme',
    'electric-appliance-selection': 'Elektrikli Eşya Seçimi',
    'pattern-3': 'Desen Kopyalama 3',
    'zebra-letters': 'Zebra Harfleri',
    'shape-matching-drawn': 'Çizilmiş Şekil Eşleştirme',
    'watermelon-math': 'Karpuz Matematiği',
    'fruit-sequence-v2': 'Meyve Dizisi 2',
    'doctor-suitability': 'Doktora Uygunluk',
    'fruit-group-matching': 'Meyve Grubu Eşleştirme',
    'orange-coloring': 'Portakal Boyama',
    'symbol-grid-counting': 'Sembol Izgarası Sayma',
    'object-count-selection': 'Nesne Sayısı Seçimi',
    'fewest-triangles': 'En Az Üçgen',
    'favorite-activity': 'Sevilen Etkinlik',
    'count-matching-v3': 'Sayı Eşleştirme 3',
    'egg-subtraction': 'Yumurta Çıkarma',
    'house-items': 'Ev Eşyaları',
    'pink-grid': 'Pembe Izgara',
    'letter-counting-v2': 'Harf Sayma 2',
    'shape-count-coloring-v2': 'Şekil Sayısına Göre Boyama 2',
    'sad-expressions': 'Üzgün İfadeler',
    'geometric-sequence': 'Geometrik Dizi',
    'finding-red-lines': 'Kırmızı Çizgileri Bulma',
    'uppercase-lowercase': 'Büyük Küçük Harf',
    'word-shape-matching': 'Kelime Şekli Eşleştirme',
    'pattern-transfer': 'Deseni Aktarma',
    'ladybug-spots': 'Uğur Böceği Noktaları',
    'rotate-grid': 'Izgarayı Döndürme',
    'color-by-number': 'Sayıya Göre Boyama',
    'toothbrush-selection': 'Diş Fırçası Seçimi',
    'symbol-addition-v2': 'Sembol Toplama 2',
    'cat-sequence': 'Kedi Dizisi',
    'missing-number-grid': 'Eksik Sayı Izgarası',
    'veg-grid-transfer': 'Sebze Izgarası Aktarma',
    'symbol-sequence-placement': 'Sembol Dizisi Yerleştirme',
};

export function questionTitle(questionId: string): string {
    return QUESTION_TITLES[questionId] ?? questionId;
}
