import { Routes } from '@angular/router';
import { authGuard, homeRedirectGuard, roleGuard, studentExamGuard } from './core/guards/auth.guard';

// `.map(...)` her satırı preload=true olarak işaretler — bkz. ExamPreloadStrategy:
// bu 150+ küçük soru chunk'ı uygulama açılır açılmaz arkaplanda indirilir, böylece
// öğrenci bir sonraki soruya geçerken chunk indirme gecikmesi/boşluğu yaşanmaz.
const examRoutesRaw: Routes = [
    { path: 'pattern', loadComponent: () => import('./features/pattern-matching/pattern-matching.component').then(m => m.PatternMatchingComponent) },
    { path: 'odd-direction', loadComponent: () => import('./features/odd-direction/odd-direction.component').then(m => m.OddDirectionComponent) },
    { path: 'shade-sorting', loadComponent: () => import('./features/shade-sorting/shade-sorting.component').then(m => m.ShadeSortingComponent) },
    { path: 'shade-sorting-2', loadComponent: () => import('./features/shade-sorting-2/shade-sorting-2.component').then(m => m.ShadeSorting2Component) },
    { path: 'number-sequence', loadComponent: () => import('./features/number-sequence/number-sequence.component').then(m => m.NumberSequenceComponent) },
    { path: 'symbol-matching', loadComponent: () => import('./features/symbol-matching/symbol-matching.component').then(m => m.SymbolMatchingComponent) },
    { path: 'multi-condition-selection', loadComponent: () => import('./features/multi-condition-selection/multi-condition-selection.component').then(m => m.MultiConditionSelectionComponent) },
    { path: 'animal-position', loadComponent: () => import('./features/animal-position/animal-position.component').then(m => m.AnimalPositionComponent) },
    { path: 'pattern-2', loadComponent: () => import('./features/pattern-matching-two/pattern-matching-two.component').then(m => m.PatternMatchingTwoComponent) },
    { path: 'shape-coloring', loadComponent: () => import('./features/shape-coloring/shape-coloring.component').then(m => m.ShapeColoringComponent) },
    { path: 'liquid-selection', loadComponent: () => import('./features/liquid-selection/liquid-selection.component').then(m => m.LiquidSelectionComponent) },
    { path: 'longest-rope', loadComponent: () => import('./features/longest-rope/longest-rope.component').then(m => m.LongestRopeComponent) },
    { path: 'letter-matching', loadComponent: () => import('./features/letter-matching/letter-matching.component').then(m => m.LetterMatchingComponent) },
    { path: 'shape-pattern', loadComponent: () => import('./features/shape-pattern/shape-pattern.component').then(m => m.ShapePatternComponent) },
    { path: 'board-letter-matching', loadComponent: () => import('./features/board-letter-matching/board-letter-matching.component').then(m => m.BoardLetterMatchingComponent) },
    { path: 'shape-to-color-match', loadComponent: () => import('./features/shape-to-color-match/shape-to-color-match.component').then(m => m.ShapeToColorMatchComponent) },
    { path: 'sequence-rule-breaker', loadComponent: () => import('./features/sequence-rule-breaker/sequence-rule-breaker.component').then(m => m.SequenceRuleBreakerComponent) },
    { path: 'living-things', loadComponent: () => import('./features/living-things/living-things').then(m => m.LivingThingsComponent) },
    { path: 'traffic-sign-matching', loadComponent: () => import('./features/traffic-sign-matching/traffic-sign-matching.component').then(m => m.TrafficSignMatchingComponent) },
    { path: 'abacus-counting', loadComponent: () => import('./features/abacus-counting/abacus-counting.component').then(m => m.AbacusCountingComponent) },
    { path: 'dot-pattern-drawing', loadComponent: () => import('./features/dot-pattern-drawing/dot-pattern-drawing.component').then(m => m.DotPatternDrawingComponent) },
    { path: 'fruit-count-matching', loadComponent: () => import('./features/fruit-count-matching/fruit-count-matching.component').then(m => m.FruitCountMatchingComponent) },
    { path: 'find-most-balls', loadComponent: () => import('./features/find-most-balls/find-most-balls.component').then(m => m.FindMostBallsComponent) },
    { path: 'shadow-matching', loadComponent: () => import('./features/shadow-matching/shadow-matching.component').then(m => m.ShadowMatchingComponent) },
    { path: 'letter-sequence', loadComponent: () => import('./features/letter-sequence/letter-sequence.component').then(m => m.LetterSequenceComponent) },
    { path: 'identical-pattern', loadComponent: () => import('./features/identical-pattern/identical-pattern.component').then(m => m.IdenticalPatternComponent) },
    { path: 'match-size', loadComponent: () => import('./features/match-size/match-size.component').then(m => m.MatchSizeComponent) },
    { path: 'grid-coloring', loadComponent: () => import('./features/grid-coloring/grid-coloring.component').then(m => m.GridColoringComponent) },
    { path: 'find-same-symbols', loadComponent: () => import('./features/find-same-symbols/find-same-symbols.component').then(m => m.FindSameSymbolsComponent) },
    { path: 'find-numbers', loadComponent: () => import('./features/find-numbers/find-numbers.component').then(m => m.FindNumbersComponent) },
    { path: 'find-reversed-e', loadComponent: () => import('./features/find-reversed-e/find-reversed-e.component').then(m => m.FindReversedEComponent) },
    { path: 'count-and-add', loadComponent: () => import('./features/count-and-add/count-and-add.component').then(m => m.CountAndAddComponent) },
    { path: 'rhythmic-counting', loadComponent: () => import('./features/rhythmic-counting/rhythmic-counting.component').then(m => m.RhythmicCountingComponent) },
    { path: 'top-view', loadComponent: () => import('./features/top-view/top-view.component').then(m => m.TopViewComponent) },
    { path: 'box-coloring', loadComponent: () => import('./features/box-coloring/box-coloring.component').then(m => m.BoxColoringComponent) },
    { path: 'triangle-size', loadComponent: () => import('./features/triangle-size/triangle-size.component').then(m => m.TriangleSizeComponent) },
    { path: 'flower-coloring', loadComponent: () => import('./features/flower-coloring/flower-coloring.component').then(m => m.FlowerColoringComponent) },
    { path: 'not-in-word', loadComponent: () => import('./features/not-in-word/not-in-word.component').then(m => m.NotInWordComponent) },
    { path: 'finding-green-lines', loadComponent: () => import('./features/finding-green-lines/finding-green-lines.component').then(m => m.FindingGreenLinesComponent) },
    { path: 'incorrect-numbers', loadComponent: () => import('./features/incorrect-numbers/incorrect-numbers.component').then(m => m.IncorrectNumbersComponent) },
    { path: 'water-capacity', loadComponent: () => import('./features/water-capacity/water-capacity.component').then(m => m.WaterCapacityComponent) },
    { path: 'fruit-size-ranking', loadComponent: () => import('./features/fruit-size-ranking/fruit-size-ranking.component').then(m => m.FruitSizeRankingComponent) },
    { path: 'elderly-people', loadComponent: () => import('./features/elderly-people/elderly-people.component').then(m => m.ElderlyPeopleComponent) },
    { path: 'find-different', loadComponent: () => import('./features/find-different/find-different.component').then(m => m.FindDifferentComponent) },
    { path: 'cylinder-selection', loadComponent: () => import('./features/cylinder-selection/cylinder-selection.component').then(m => m.CylinderSelectionComponent) },
    { path: 'pattern-completion', loadComponent: () => import('./features/pattern-completion/pattern-completion.component').then(m => m.PatternCompletionComponent) },
    { path: 'shape-counting', loadComponent: () => import('./features/shape-counting/shape-counting.component').then(m => m.ShapeCountingComponent) },
    { path: 'happy-children', loadComponent: () => import('./features/happy-children/happy-children.component').then(m => m.HappyChildrenComponent) },
    { path: 'different-mountain', loadComponent: () => import('./features/different-mountain/different-mountain.component').then(m => m.DifferentMountainComponent) },
    { path: 'letter-grid', loadComponent: () => import('./features/letter-grid/letter-grid.component').then(m => m.LetterGridComponent) },
    { path: 'ice-cream-shape', loadComponent: () => import('./features/ice-cream-shape/ice-cream-shape.component').then(m => m.IceCreamShapeComponent) },
    { path: 'school-profession', loadComponent: () => import('./features/school-profession/school-profession.component').then(m => m.SchoolProfessionComponent) },
    { path: 'tallest-animal', loadComponent: () => import('./features/tallest-animal/tallest-animal.component').then(m => m.TallestAnimalComponent) },
    { path: 'shape-corners', loadComponent: () => import('./features/shape-corners/shape-corners.component').then(m => m.ShapeCornersComponent) },
    { path: 'pencil-matching-v2', loadComponent: () => import('./features/pencil-matching-v2/pencil-matching-v2.component').then(m => m.PencilMatchingV2Component) },
    { path: 'shape-count-coloring', loadComponent: () => import('./features/shape-count-coloring/shape-count-coloring.component').then(m => m.ShapeCountColoringComponent) },
    { path: 'sport-matching', loadComponent: () => import('./features/sport-matching/sport-matching.component').then(m => m.SportMatchingComponent) },
    { path: 'letter-counting', loadComponent: () => import('./features/letter-counting/letter-counting.component').then(m => m.LetterCountingComponent) },
    { path: 'elephant-direction', loadComponent: () => import('./features/elephant-direction/elephant-direction.component').then(m => m.ElephantDirectionComponent) },
    { path: 'symbol-addition', loadComponent: () => import('./features/symbol-addition/symbol-addition.component').then(m => m.SymbolAdditionComponent) },
    { path: 'grid-coloring-numbers', loadComponent: () => import('./features/grid-coloring-numbers/grid-coloring-numbers.component').then(m => m.GridColoringNumbersComponent) },
    { path: 'child-bicycle-matching', loadComponent: () => import('./features/child-bicycle-matching/child-bicycle-matching.component').then(m => m.ChildBicycleMatchingComponent) },
    { path: 'symbol-pair-matching', loadComponent: () => import('./features/symbol-pair-matching/symbol-pair-matching.component').then(m => m.SymbolPairMatchingComponent) },
    { path: 'house-door-direction', loadComponent: () => import('./features/house-door-direction/house-door-direction.component').then(m => m.HouseDoorDirectionComponent) },
    { path: 'count-matching-v2', loadComponent: () => import('./features/count-matching-v2/count-matching-v2.component').then(m => m.CountMatchingV2Component) },
    { path: 'rectangle-selection', loadComponent: () => import('./features/rectangle-selection/rectangle-selection.component').then(m => m.RectangleSelectionComponent) },
    { path: 'count-six-selection', loadComponent: () => import('./features/count-six-selection/count-six-selection.component').then(m => m.CountSixSelectionComponent) },
    { path: 'electric-appliance-selection', loadComponent: () => import('./features/electric-appliance-selection/electric-appliance-selection.component').then(m => m.ElectricApplianceSelectionComponent) },
    { path: 'pattern-3', loadComponent: () => import('./features/pattern-matching-three/pattern-matching-three.component').then(m => m.PatternMatchingThreeComponent) },
    { path: 'zebra-letters', loadComponent: () => import('./features/zebra-letter-selection/zebra-letter-selection.component').then(m => m.ZebraLetterSelectionComponent) },
    { path: 'shape-matching-drawn', loadComponent: () => import('./features/shape-matching-drawn/shape-matching-drawn.component').then(m => m.ShapeMatchingDrawnComponent) },
    { path: 'watermelon-math', loadComponent: () => import('./features/watermelon-math/watermelon-math.component').then(m => m.WatermelonMathComponent) },
    { path: 'fruit-sequence-v2', loadComponent: () => import('./features/fruit-sequence-v2/fruit-sequence-v2.component').then(m => m.FruitSequenceV2Component) },
    { path: 'doctor-suitability', loadComponent: () => import('./features/doctor-suitability/doctor-suitability.component').then(m => m.DoctorSuitabilityComponent) },
    { path: 'fruit-group-matching', loadComponent: () => import('./features/fruit-group-matching/fruit-group-matching.component').then(m => m.FruitGroupMatchingComponent) },
    { path: 'orange-coloring', loadComponent: () => import('./features/orange-coloring/orange-coloring.component').then(m => m.OrangeColoringComponent) },
    { path: 'symbol-grid-counting', loadComponent: () => import('./features/symbol-grid-counting/symbol-grid-counting.component').then(m => m.SymbolGridCountingComponent) },
    { path: 'object-count-selection', loadComponent: () => import('./features/object-count-selection/object-count-selection.component').then(m => m.ObjectCountSelectionComponent) },
    { path: 'fewest-triangles', loadComponent: () => import('./features/fewest-triangles/fewest-triangles.component').then(m => m.FewestTrianglesComponent) },
    { path: 'favorite-activity', loadComponent: () => import('./features/favorite-activity/favorite-activity.component').then(m => m.FavoriteActivityComponent) },
    { path: 'count-matching-v3', loadComponent: () => import('./features/count-matching-v3/count-matching-v3.component').then(m => m.CountMatchingV3Component) },
    { path: 'egg-subtraction', loadComponent: () => import('./features/egg-subtraction/egg-subtraction.component').then(m => m.EggSubtractionComponent) },
    { path: 'house-items', loadComponent: () => import('./features/house-items/house-items.component').then(m => m.HouseItemsComponent) },
    { path: 'pink-grid', loadComponent: () => import('./features/pink-grid/pink-grid.component').then(m => m.PinkGridComponent) },
    { path: 'letter-counting-v2', loadComponent: () => import('./features/letter-counting-v2/letter-counting-v2.component').then(m => m.LetterCountingV2Component) },
    { path: 'shape-count-coloring-v2', loadComponent: () => import('./features/shape-count-coloring-v2/shape-count-coloring-v2.component').then(m => m.ShapeCountColoringV2Component) },
    { path: 'sad-expressions', loadComponent: () => import('./features/sad-expressions/sad-expressions.component').then(m => m.SadExpressionsComponent) },
    { path: 'geometric-sequence', loadComponent: () => import('./features/geometric-sequence/geometric-sequence.component').then(m => m.GeometricSequenceComponent) },
    { path: 'finding-red-lines', loadComponent: () => import('./features/finding-red-lines/finding-red-lines.component').then(m => m.FindingRedLinesComponent) },
    { path: 'uppercase-lowercase', loadComponent: () => import('./features/uppercase-lowercase/uppercase-lowercase.component').then(m => m.UppercaseLowercaseComponent) },
    { path: 'word-shape-matching', loadComponent: () => import('./features/word-shape-matching/word-shape-matching.component').then(m => m.WordShapeMatchingComponent) },
    { path: 'pattern-transfer', loadComponent: () => import('./features/pattern-transfer/pattern-transfer.component').then(m => m.PatternTransferComponent) },
    { path: 'ladybug-spots', loadComponent: () => import('./features/ladybug-spots/ladybug-spots.component').then(m => m.LadybugSpotsComponent) },
    { path: 'rotate-grid', loadComponent: () => import('./features/rotate-grid/rotate-grid.component').then(m => m.RotateGridComponent) },
    { path: 'color-by-number', loadComponent: () => import('./features/color-by-number/color-by-number.component').then(m => m.ColorByNumberComponent) },
    { path: 'toothbrush-selection', loadComponent: () => import('./features/toothbrush-selection/toothbrush-selection.component').then(m => m.ToothbrushSelectionComponent) },
    { path: 'symbol-addition-v2', loadComponent: () => import('./features/symbol-addition-v2/symbol-addition-v2.component').then(m => m.SymbolAdditionV2Component) },
    { path: 'cat-sequence', loadComponent: () => import('./features/cat-sequence/cat-sequence.component').then(m => m.CatSequenceComponent) },
    { path: 'missing-number-grid', loadComponent: () => import('./features/missing-number-grid/missing-number-grid.component').then(m => m.MissingNumberGridComponent) },
    { path: 'veg-grid-transfer', loadComponent: () => import('./features/veg-grid-transfer/veg-grid-transfer.component').then(m => m.VegGridTransferComponent) },
    { path: 'symbol-sequence-placement', loadComponent: () => import('./features/symbol-sequence-placement/symbol-sequence-placement.component').then(m => m.SymbolSequencePlacementComponent) },
    { path: 'most-colorful-ball', loadComponent: () => import('./features/most-colorful-ball/most-colorful-ball.component').then(m => m.MostColorfulBallComponent) },
    { path: 'cat-position', loadComponent: () => import('./features/cat-position/cat-position.component').then(m => m.CatPositionComponent) },
    { path: 'dot-grid-copy', loadComponent: () => import('./features/dot-grid-copy/dot-grid-copy.component').then(m => m.DotGridCopyComponent) },
    { path: 'bike-matching', loadComponent: () => import('./features/bike-matching/bike-matching.component').then(m => m.BikeMatchingComponent) },
    { path: 'pencil-matching', loadComponent: () => import('./features/pencil-matching/pencil-matching.component').then(m => m.PencilMatchingComponent) },
    { path: 'symbol-grid-copy', loadComponent: () => import('./features/symbol-grid-copy/symbol-grid-copy.component').then(m => m.SymbolGridCopyComponent) },
    { path: 'ball-matching', loadComponent: () => import('./features/ball-matching/ball-matching.component').then(m => m.BallMatchingComponent) },
    { path: 'orange-different', loadComponent: () => import('./features/orange-different/orange-different.component').then(m => m.OrangeDifferentComponent) },
    { path: 'river-branches', loadComponent: () => import('./features/river-branches/river-branches.component').then(m => m.RiverBranchesComponent) },
    { path: 'symbol-grid-matching', loadComponent: () => import('./features/symbol-grid-matching/symbol-grid-matching.component').then(m => m.SymbolGridMatchingComponent) },
    { path: 'shape-match-find', loadComponent: () => import('./features/shape-match-find/shape-match-find.component').then(m => m.ShapeMatchFindComponent) },
    { path: 'count-apples', loadComponent: () => import('./features/count-apples/count-apples.component').then(m => m.CountApplesComponent) },
    { path: 'ball-sequence', loadComponent: () => import('./features/ball-sequence/ball-sequence.component').then(m => m.BallSequenceComponent) },
    { path: 'snake-letter', loadComponent: () => import('./features/snake-letter/snake-letter.component').then(m => m.SnakeLetterComponent) },
    { path: 'letter-color-match', loadComponent: () => import('./features/letter-color-match/letter-color-match.component').then(m => m.LetterColorMatchComponent) },
    { path: 'fruit-subtraction', loadComponent: () => import('./features/fruit-subtraction/fruit-subtraction.component').then(m => m.FruitSubtractionComponent) },
    { path: 'triangle-match', loadComponent: () => import('./features/triangle-match/triangle-match.component').then(m => m.TriangleMatchComponent) },
    { path: 'set-match', loadComponent: () => import('./features/set-match/set-match.component').then(m => m.SetMatchComponent) },
    { path: 'profession-matching', loadComponent: () => import('./features/profession-matching/profession-matching.component').then(m => m.ProfessionMatchingComponent) },
    { path: 'fruit-basket', loadComponent: () => import('./features/fruit-basket/fruit-basket.component').then(m => m.FruitBasketComponent) },
    { path: 'flower-order', loadComponent: () => import('./features/flower-order/flower-order.component').then(m => m.FlowerOrderComponent) },
    { path: 'symbol-color-match', loadComponent: () => import('./features/symbol-color-match/symbol-color-match.component').then(m => m.SymbolColorMatchComponent) },
    { path: 'object-addition', loadComponent: () => import('./features/object-addition/object-addition.component').then(m => m.ObjectAdditionComponent) },
    { path: 'symbol-block-match', loadComponent: () => import('./features/symbol-block-match/symbol-block-match.component').then(m => m.SymbolBlockMatchComponent) },
    { path: 'balance-scale', loadComponent: () => import('./features/balance-scale/balance-scale.component').then(m => m.BalanceScaleComponent) },
    { path: 'two-feature-filter', loadComponent: () => import('./features/two-feature-filter/two-feature-filter.component').then(m => m.TwoFeatureFilterComponent) },
    { path: 'subtle-difference', loadComponent: () => import('./features/subtle-difference/subtle-difference.component').then(m => m.SubtleDifferenceComponent) },
    { path: 'letter-hunt', loadComponent: () => import('./features/letter-hunt/letter-hunt.component').then(m => m.LetterHuntComponent) },
    { path: 'missing-number', loadComponent: () => import('./features/missing-number/missing-number.component').then(m => m.MissingNumberComponent) },
    { path: 'odd-category-out', loadComponent: () => import('./features/odd-category-out/odd-category-out.component').then(m => m.OddCategoryOutComponent) },
    { path: 'mirror-letter', loadComponent: () => import('./features/mirror-letter/mirror-letter.component').then(m => m.MirrorLetterComponent) },
    { path: 'letter-count', loadComponent: () => import('./features/letter-count/letter-count.component').then(m => m.LetterCountComponent) },
    { path: 'first-letter-match', loadComponent: () => import('./features/first-letter-match/first-letter-match.component').then(m => m.FirstLetterMatchComponent) },
    { path: 'count-difference', loadComponent: () => import('./features/count-difference/count-difference.component').then(m => m.CountDifferenceComponent) },
    { path: 'number-ordering', loadComponent: () => import('./features/number-ordering/number-ordering.component').then(m => m.NumberOrderingComponent) },
    { path: 'rotate-shape', loadComponent: () => import('./features/rotate-shape/rotate-shape.component').then(m => m.RotateShapeComponent) },
    { path: 'count-sides', loadComponent: () => import('./features/count-sides/count-sides.component').then(m => m.CountSidesComponent) },
    { path: 'sort-by-size', loadComponent: () => import('./features/sort-by-size/sort-by-size.component').then(m => m.SortBySizeComponent) },
    { path: 'same-word-find', loadComponent: () => import('./features/same-word-find/same-word-find.component').then(m => m.SameWordFindComponent) },
    { path: 'count-given-color', loadComponent: () => import('./features/count-given-color/count-given-color.component').then(m => m.CountGivenColorComponent) },
    { path: 'star-difference', loadComponent: () => import('./features/star-difference/star-difference.component').then(m => m.StarDifferenceComponent) },
    { path: 'fruit-sequence', loadComponent: () => import('./features/fruit-sequence/fruit-sequence.component').then(m => m.FruitSequenceComponent) },
    { path: 'arrow-grid-copy', loadComponent: () => import('./features/arrow-grid-copy/arrow-grid-copy.component').then(m => m.ArrowGridCopyComponent) },
    { path: 'color-pattern-completion', loadComponent: () => import('./features/color-pattern-completion/color-pattern-completion.component').then(m => m.ColorPatternCompletionComponent) },
    { path: 'number-grid-match', loadComponent: () => import('./features/number-grid-match/number-grid-match.component').then(m => m.NumberGridMatchComponent) },
    { path: 'digit-row-finder', loadComponent: () => import('./features/digit-row-finder/digit-row-finder.component').then(m => m.DigitRowFinderComponent) },
    { path: 'number-color-match', loadComponent: () => import('./features/number-color-match/number-color-match.component').then(m => m.NumberColorMatchComponent) },
    { path: 'symbol-sequence-match', loadComponent: () => import('./features/symbol-sequence-match/symbol-sequence-match.component').then(m => m.SymbolSequenceMatchComponent) },
    { path: 'shape-matrix', loadComponent: () => import('./features/shape-matrix/shape-matrix.component').then(m => m.ShapeMatrixComponent) },
    { path: 'end', loadComponent: () => import('./features/end-page/end-page.component').then(m => m.EndPageComponent) },
];

export const examRoutes: Routes = examRoutesRaw.map(r => ({ ...r, data: { ...r.data, preload: true } }));

export const routes: Routes = [
    {
        path: '',
        pathMatch: 'full',
        canActivate: [homeRedirectGuard],
        children: [],
    },
    {
        path: 'login',
        loadComponent: () => import('./portal/auth/login/login.component').then(m => m.LoginComponent),
    },
    {
        path: 'admin',
        canActivate: [authGuard, roleGuard('admin')],
        loadComponent: () => import('./portal/admin/admin-dashboard.component').then(m => m.AdminDashboardComponent),
        children: [
            { path: '', pathMatch: 'full', redirectTo: 'overview' },
            { path: 'overview', loadComponent: () => import('./portal/admin/overview/admin-overview.component').then(m => m.AdminOverviewComponent) },
            { path: 'teachers', loadComponent: () => import('./portal/admin/teachers/admin-teachers.component').then(m => m.AdminTeachersComponent) },
            { path: 'students', loadComponent: () => import('./portal/admin/students/admin-students.component').then(m => m.AdminStudentsComponent) },
            { path: 'questions', loadComponent: () => import('./portal/admin/questions/admin-questions.component').then(m => m.AdminQuestionsComponent) },
            // Eski "Sınav Yönetimi" adresi — içeriği artık /admin/questions
            // sekmelerinde; kayıtlı bağlantılar kırılmasın diye yönlendiriliyor.
            { path: 'exams', pathMatch: 'full', redirectTo: 'questions' },
            { path: 'settings', loadComponent: () => import('./portal/admin/settings/admin-settings.component').then(m => m.AdminSettingsComponent) },
            { path: 'teachers/:id', loadComponent: () => import('./portal/admin/admin-teacher-detail.component').then(m => m.AdminTeacherDetailComponent) },
        ],
    },
    {
        // Yönetici de aynı inceleme ekranını kullanır (component rol-duyarlı).
        path: 'admin/students/:id/review',
        canActivate: [authGuard, roleGuard('admin')],
        loadComponent: () => import('./portal/teacher/teacher-review.component').then(m => m.TeacherReviewComponent),
    },
    {
        path: 'teacher',
        canActivate: [authGuard, roleGuard('teacher')],
        loadComponent: () => import('./portal/teacher/teacher-dashboard.component').then(m => m.TeacherDashboardComponent),
        children: [
            { path: '', pathMatch: 'full', redirectTo: 'overview' },
            { path: 'overview', loadComponent: () => import('./portal/teacher/overview/teacher-overview.component').then(m => m.TeacherOverviewComponent) },
            { path: 'students', loadComponent: () => import('./portal/teacher/students/teacher-students.component').then(m => m.TeacherStudentsComponent) },
            { path: 'questions', loadComponent: () => import('./portal/teacher/questions/teacher-questions.component').then(m => m.TeacherQuestionsComponent) },
        ],
    },
    {
        path: 'teacher/students/:id/review',
        canActivate: [authGuard, roleGuard('teacher')],
        loadComponent: () => import('./portal/teacher/teacher-review.component').then(m => m.TeacherReviewComponent),
    },
    {
        path: 'student/exam',
        canActivate: [authGuard, roleGuard('student')],
        loadComponent: () => import('./portal/student/student-exam-home.component').then(m => m.StudentExamHomeComponent),
    },
    {
        // Mevcut 150 etkinlik rotası aynı düz path'lerde kalır; canActivateChild öğrenciyi
        // yalnızca sırası gelen soruya izin verir, öğretmen/yönetici serbestçe gezinebilir.
        path: '',
        canActivate: [authGuard],
        canActivateChild: [studentExamGuard],
        children: examRoutes,
    },
    { path: '**', redirectTo: '' },
];
